// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsHkDJFb-wBdSfXQqhKd8eXL_Fn-qUPq0',
    appId: '1:621835959511:web:30080f97f62fc508808492',
    messagingSenderId: '621835959511',
    projectId: 'todoapp-bc651',
    authDomain: 'todoapp-bc651.firebaseapp.com',
    storageBucket: 'todoapp-bc651.firebasestorage.app',
    measurementId: 'G-0G6WV2MSV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH94ZwrC2hqUuLL43qO63TDZewBDJ8Irc',
    appId: '1:621835959511:android:69194868a02d82b1808492',
    messagingSenderId: '621835959511',
    projectId: 'todoapp-bc651',
    storageBucket: 'todoapp-bc651.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKmWm8_E5k34KaR0j4lvO2afuJRlGCtwc',
    appId: '1:621835959511:ios:cbbed8aeb0d284c8808492',
    messagingSenderId: '621835959511',
    projectId: 'todoapp-bc651',
    storageBucket: 'todoapp-bc651.firebasestorage.app',
    iosBundleId: 'com.example.todoapp.todoAppJitendra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKmWm8_E5k34KaR0j4lvO2afuJRlGCtwc',
    appId: '1:621835959511:ios:cbbed8aeb0d284c8808492',
    messagingSenderId: '621835959511',
    projectId: 'todoapp-bc651',
    storageBucket: 'todoapp-bc651.firebasestorage.app',
    iosBundleId: 'com.example.todoapp.todoAppJitendra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsHkDJFb-wBdSfXQqhKd8eXL_Fn-qUPq0',
    appId: '1:621835959511:web:25a9d26c19faa282808492',
    messagingSenderId: '621835959511',
    projectId: 'todoapp-bc651',
    authDomain: 'todoapp-bc651.firebaseapp.com',
    storageBucket: 'todoapp-bc651.firebasestorage.app',
    measurementId: 'G-MQDXTS22HG',
  );
}
